name: agriconnect_pro
description: AgriConnect Pro — Smart farming in your pocket.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.0
  groq_sdk: ^1.0.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  intl: ^0.19.0
  geolocator: ^11.0.0
  image_picker: ^1.2.2
  connectivity_plus: ^7.1.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  supabase_flutter: ^2.12.4


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
